/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "common.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void Identifier_Initialize(Identifier pVal)
{
    static Identifier ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag Identifier_IsConstraintValid(const Identifier pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= strlen(pVal) && strlen(pVal) <= 32);
	*pErrCode = ret ? 0 : ERR_Identifier;

	return ret;
}

flag Identifier_Encode(const Identifier pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? Identifier_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, strlen(pVal), 1, 32);
	    	
	    for(i1=0; (i1 < (int)strlen(pVal)) && ret; i1++) 
	    {
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal[i1], 0, 127);
	    }
    }

	return ret;
}

flag Identifier_Decode(Identifier pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 32);
		
	for(i1=0; (i1 < (int)nCount) && ret; i1++) 
	{
		asn1SccSint charValue=0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charValue, 0, 127);
		*pErrCode = ret ? 0 : 268435457;
		pVal[i1] = (char)charValue;
	}
	pVal[nCount] = 0x0;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void FilePath_Initialize(FilePath pVal)
{
    static FilePath ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag FilePath_IsConstraintValid(const FilePath pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= strlen(pVal) && strlen(pVal) <= 256);
	*pErrCode = ret ? 0 : ERR_FilePath;

	return ret;
}

flag FilePath_Encode(const FilePath pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? FilePath_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, strlen(pVal), 1, 256);
	    	
	    for(i1=0; (i1 < (int)strlen(pVal)) && ret; i1++) 
	    {
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal[i1], 0, 127);
	    }
    }

	return ret;
}

flag FilePath_Decode(FilePath pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 256);
		
	for(i1=0; (i1 < (int)nCount) && ret; i1++) 
	{
		asn1SccSint charValue=0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charValue, 0, 127);
		*pErrCode = ret ? 0 : 268435458;
		pVal[i1] = (char)charValue;
	}
	pVal[nCount] = 0x0;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void FileName_Initialize(FileName pVal)
{
    static FileName ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag FileName_IsConstraintValid(const FileName pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= strlen(pVal) && strlen(pVal) <= 128);
	*pErrCode = ret ? 0 : ERR_FileName;

	return ret;
}

flag FileName_Encode(const FileName pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? FileName_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, strlen(pVal), 1, 128);
	    	
	    for(i1=0; (i1 < (int)strlen(pVal)) && ret; i1++) 
	    {
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, pVal[i1], 0, 127);
	    }
    }

	return ret;
}

flag FileName_Decode(FileName pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nCount;
	int i1=0;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nCount, 1, 128);
		
	for(i1=0; (i1 < (int)nCount) && ret; i1++) 
	{
		asn1SccSint charValue=0;
		ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &charValue, 0, 127);
		*pErrCode = ret ? 0 : 268435459;
		pVal[i1] = (char)charValue;
	}
	pVal[nCount] = 0x0;

	return ret;
}

