/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "secondary_config.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void ECUSerial_Initialize(ECUSerial pVal)
{
    static ECUSerial ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag ECUSerial_IsConstraintValid(const ECUSerial pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = Identifier_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag ECUSerial_Encode(const ECUSerial pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? ECUSerial_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = Identifier_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag ECUSerial_Decode(ECUSerial pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = Identifier_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void ECUHardwareId_Initialize(ECUHardwareId pVal)
{
    static ECUHardwareId ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag ECUHardwareId_IsConstraintValid(const ECUHardwareId pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = Identifier_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag ECUHardwareId_Encode(const ECUHardwareId pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? ECUHardwareId_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = Identifier_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag ECUHardwareId_Decode(ECUHardwareId pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = Identifier_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void SecondaryType_Initialize(SecondaryType* pVal)
{
    *pVal = (SecondaryType) virtual;
}
#endif

 
flag SecondaryType_IsConstraintValid(const SecondaryType* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (((*pVal == virtual) || (*pVal == legacy)) || (*pVal == uptane));
	*pErrCode = ret ? 0 : ERR_SecondaryType;

	return ret;
}

flag SecondaryType_Encode(const SecondaryType* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? SecondaryType_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case virtual:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	        	break;
	        case legacy:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	        	break;
	        case uptane:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	        	break;
	        default:
	    	    *pErrCode = 1074003969; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag SecondaryType_Decode(SecondaryType* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 2);
	*pErrCode = ret ? 0 : 268697601;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = virtual;
	            break;
	        case 1: 
	            *pVal = legacy;
	            break;
	        case 2: 
	            *pVal = uptane;
	            break;
	        default:
		        *pErrCode = 1074003970;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void SecondaryConfig_Initialize(SecondaryConfig* pVal)
{
    *pVal = (SecondaryConfig) {
    .secondaryType = virtual,
    .partialVerifying = FALSE,
    .ecuSerial = " ",
    .ecuHardwareId = " ",
    .fullClientDir = " ",
    .ecuPrivateKey = " ",
    .ecuPublicKey = " ",
    .firmwarePath = " ",
    .targetNamePath = " ",
    .metadataPath = " "
};
}
#endif

 
flag SecondaryConfig_IsConstraintValid(const SecondaryConfig* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = SecondaryType_IsConstraintValid(&pVal->secondaryType, pErrCode);
	if (ret) {
	    ret = TRUE; *pErrCode = 0;
	    if (ret) {
	        ret = ECUSerial_IsConstraintValid(pVal->ecuSerial, pErrCode);
	        if (ret) {
	            ret = ECUHardwareId_IsConstraintValid(pVal->ecuHardwareId, pErrCode);
	            if (ret) {
	                ret = FilePath_IsConstraintValid(pVal->fullClientDir, pErrCode);
	                if (ret) {
	                    ret = FileName_IsConstraintValid(pVal->ecuPrivateKey, pErrCode);
	                    if (ret) {
	                        ret = FileName_IsConstraintValid(pVal->ecuPublicKey, pErrCode);
	                        if (ret) {
	                            ret = FilePath_IsConstraintValid(pVal->firmwarePath, pErrCode);
	                            if (ret) {
	                                ret = FilePath_IsConstraintValid(pVal->targetNamePath, pErrCode);
	                                if (ret) {
	                                    ret = FilePath_IsConstraintValid(pVal->metadataPath, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag SecondaryConfig_Encode(const SecondaryConfig* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? SecondaryConfig_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode secondaryType */
	    ret = SecondaryType_Encode(&pVal->secondaryType, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode partialVerifying */
	        BitStream_AppendBit(pBitStrm,pVal->partialVerifying);
	        if (ret) {
	            /*Encode ecuSerial */
	            ret = ECUSerial_Encode(pVal->ecuSerial, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode ecuHardwareId */
	                ret = ECUHardwareId_Encode(pVal->ecuHardwareId, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode fullClientDir */
	                    ret = FilePath_Encode(pVal->fullClientDir, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode ecuPrivateKey */
	                        ret = FileName_Encode(pVal->ecuPrivateKey, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode ecuPublicKey */
	                            ret = FileName_Encode(pVal->ecuPublicKey, pBitStrm, pErrCode, FALSE);
	                            if (ret) {
	                                /*Encode firmwarePath */
	                                ret = FilePath_Encode(pVal->firmwarePath, pBitStrm, pErrCode, FALSE);
	                                if (ret) {
	                                    /*Encode targetNamePath */
	                                    ret = FilePath_Encode(pVal->targetNamePath, pBitStrm, pErrCode, FALSE);
	                                    if (ret) {
	                                        /*Encode metadataPath */
	                                        ret = FilePath_Encode(pVal->metadataPath, pBitStrm, pErrCode, FALSE);
	                                    
	                                    }
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag SecondaryConfig_Decode(SecondaryConfig* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode secondaryType */
	ret = SecondaryType_Decode(&pVal->secondaryType, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode partialVerifying */
	    ret = BitStream_ReadBit(pBitStrm, &pVal->partialVerifying);
	    *pErrCode = ret ? 0 : 268697602;
	    if (ret) {
	        /*Decode ecuSerial */
	        ret = ECUSerial_Decode(pVal->ecuSerial, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode ecuHardwareId */
	            ret = ECUHardwareId_Decode(pVal->ecuHardwareId, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode fullClientDir */
	                ret = FilePath_Decode(pVal->fullClientDir, pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode ecuPrivateKey */
	                    ret = FileName_Decode(pVal->ecuPrivateKey, pBitStrm, pErrCode);
	                    if (ret) {
	                        /*Decode ecuPublicKey */
	                        ret = FileName_Decode(pVal->ecuPublicKey, pBitStrm, pErrCode);
	                        if (ret) {
	                            /*Decode firmwarePath */
	                            ret = FilePath_Decode(pVal->firmwarePath, pBitStrm, pErrCode);
	                            if (ret) {
	                                /*Decode targetNamePath */
	                                ret = FilePath_Decode(pVal->targetNamePath, pBitStrm, pErrCode);
	                                if (ret) {
	                                    /*Decode metadataPath */
	                                    ret = FilePath_Decode(pVal->metadataPath, pBitStrm, pErrCode);
	                                
	                                }
	                            }
	                        }
	                    }
	                }
	            }
	        }
	    }
	}


	return ret;
}

