[tls]
server_url_path = "/var/sota/import/gateway.url"

[storage]
type = "sqlite"

[import]
base_path = "/var/sota/import"
tls_cacert_path = "root.crt"
tls_clientcert_path = "client.pem"
tls_pkey_path = "pkey.pem"
