= Key concepts

Libaktualizr provides a C++ API for getting information about currently running OTA campaigns and available updates, as well as downloading and installing the updates.

Most of the API calls, unless specified otherwise, are asynchronous and return `std::future`. The commands will be posted to the command queue and executed sequentially in a separate thread in the same order as the issued calls.

== API

=== General management, configuration and control flow

[source,cpp]
Aktualizr::Aktualizr(Config &config)

Constructs an Aktualizr instance based on the provided Config.
A minimal config should contain path to the credentials for communication
with the backend, and to the local storage which will be used to store updates and metadata.

IMPORTANT: Consider an Aktualizr(std::filesystem::path config) constructor.

.An example of a minimal config
[NOTE]
====
 [provision]
 provision_path = "/home/ota/credentials.zip"
 primary_ecu_hardware_id = "TCU"
 [storage]
 path = "/home/ota/sota-prov"
 [pacman]
 type = "none"
====
More information on configuration can be found in <<docs/configuration.adoc>>


[source,cpp]
void Aktualizr::AddSecondary(const std::shared_ptr<Uptane::SecondaryInterface> &secondary)

description

[source,cpp]
boost::signals2::connection Aktualizr::SetSignalHandler(std::function<void(shared_ptr<event::BaseEvent>)> &handler)

description

[source,cpp]
void Aktualizr::Initialize()

description

[source,cpp]
void Aktualizr::Pause()

Requests the currently running command to pause and freezes the command queue.
All commands that were scheduled after the currently executes command will wait
in the command queue until Resume() is issued.
Commands that are issued after Pause() will be put on a command queue,
but not executed until Resume().

The Pause() function returns immediately, while the paused command still may be running.

The function has no effect in case execution was already paused.

[source,cpp]
void Aktualizr::Resume()

Resumes the execution of a previously paused command and all subsequent commands in the command queue.
Returns immediately. The function has no effect if the execution is not paused.

description

[source,cpp]
void Aktualizr::Abort()

IMPORTANT: new

Requests the currently running command to abort and flushes the command queue.
The Abort() function will block until the command queue is empty and no command
is in executed state.

Can also be called on a previously paused instance, but doesn't change it's paused state.
If a paused command was aborted, next time it will start the execution
from the place it was paused.

[source,cpp]
void Aktualizr::Shutdown()

WARNING: to be removed

[source,cpp]
Aktualizr::~Aktualizr(Config &config)

description

=== Update management commands

[source,cpp]
std::future<void> Aktualizr::SendDeviceData()

description

[source,cpp]
std::future<result::UpdateCheck> Aktualizr::CheckUpdates()

description

[source,cpp]
std::future<result::Download> Aktualizr::Download(const std::vector<Uptane::Target> &updates)

description

[source,cpp]
std::future<result::Install> Aktualizr::Install(const std::vector<Uptane::Target> &updates)

description

[source,cpp]
std::unique_ptr<StorageTargetRHandle> Aktualizr::GetStoredTarget(const Uptane::Target &target) {

CAUTION: consider removing or refactoring.

=== Campaign management commands

[source,cpp]
std::future<result::CampaignCheck> Aktualizr::CampaignCheck()

description

[source,cpp]
std::future<void> Aktualizr::CampaignAccept(const std::string &campaign_id)

description

=== Miscellaneous

[source,cpp]
void Aktualizr::UptaneCycle()

description

[source,cpp]
std::future<void> Aktualizr::RunForever()

description

