= Key concepts

Libaktualizr provides a C++ API for getting information about currently running
OTA campaigns and available updates, as well as downloading and
installing the updates.

Most of the API calls, unless specified otherwise, are asynchronous and return
`std::future`. The commands will be posted to the command queue and executed
sequentially in a separate thread in the same order as the issued calls.

== API

=== General management, configuration and control flow

[source,cpp]
Aktualizr::Aktualizr(Config &config)

Constructs an Aktualizr instance based on the provided Config.
A minimal config should contain path to the credentials for communication
with the backend, and to the local storage which will be used to store updates
and metadata.

IMPORTANT: Consider an Aktualizr(std::filesystem::path config) constructor.

[source,cpp]
void Aktualizr::AddSecondary(const std::shared_ptr<Uptane::SecondaryInterface> &secondary)

Add new secondary to aktualizr. Must be called before Initialize.

[source,cpp]
void Aktualizr::Initialize()

Initialize aktualizr. Any secondaries should be added before making this
call. This will provision with the server if required. This must be called
before using any other aktualizr functions except AddSecondary.

[source,cpp]
boost::signals2::connection Aktualizr::SetSignalHandler(std::function<void(shared_ptr<event::BaseEvent>)> &handler)

Set a callback to receive event notifications.
Returns a signal connection object, which can be disconnected if desired.

[source,cpp]
void Aktualizr::Pause()

Requests the currently running command to pause and freezes the command queue.
All commands that were scheduled after the currently executed command will wait
in the command queue until Resume() is issued.
Commands that are issued after Pause() will be put on a command queue,
but not executed until Resume() is called.

The Pause() function returns immediately, while pausing the running command
still may be in progress.

The function has no effect in case execution was already paused.

[source,cpp]
void Aktualizr::Resume()

Resumes the execution of a previously paused command and all subsequent commands
in the command queue.
Returns immediately. The function has no effect if the execution was not paused.

[source,cpp]
void Aktualizr::Abort()

IMPORTANT: new

Requests the currently running command to abort and flushes the command queue.
The Abort() function will block until the command queue is empty and no command
is in executed state.

Can also be called on a previously paused instance, but doesn't change
it's paused state.
If a paused command was aborted, next time it will start the execution
from the place it was paused.

[source,cpp]
void Aktualizr::Shutdown()

WARNING: to be removed

[source,cpp]
Aktualizr::~Aktualizr(Config &config)

Calls Abort() and destroys the aktualizr object.

=== Update management commands

[source,cpp]
std::future<void> Aktualizr::SendDeviceData()

Sends local device data to the server.
This includes network status, installed packages, hardware etc.

[source,cpp]
std::future<result::UpdateCheck> Aktualizr::CheckUpdates()

Fetch Uptane metadata and check for updates.
This collects a client manifest, PUTs it to the director, updates the
Uptane metadata (including root and targets), and then checks the metadata
for target updates.

[source,cpp]
std::future<result::Download> Aktualizr::Download(const std::vector<Uptane::Target> &updates)

Download targets specified in the input vector that were previously
returned by CheckUpdates.

[source,cpp]
std::future<result::Install> Aktualizr::Install(const std::vector<Uptane::Target> &updates)

Install previously downloaded targets.

[source,cpp]
std::unique_ptr<StorageTargetRHandle> Aktualizr::GetStoredTarget(const Uptane::Target &target)

CAUTION: consider removing or refactoring.

=== Campaign management commands

[source,cpp]
std::future<result::CampaignCheck> Aktualizr::CampaignCheck()

Check for campaigns.
Campaigns are a concept outside of Uptane, and allow for user approval of
updates before the contents of the update are known.

[source,cpp]
std::future<void> Aktualizr::CampaignAccept(const std::string &campaign_id)

Accept a campaign for the current device.
Campaigns are a concept outside of Uptane, and allow for user approval of
updates before the contents of the update are known.


=== Miscellaneous

[source,cpp]
void Aktualizr::UptaneCycle()

Synchronously run an uptane cycle: check for updates, download any new
targets, install them, and send a manifest back to the server.

[source,cpp]
std::future<void> Aktualizr::RunForever()

Asynchronously run aktualizr indefinitely until Shutdown is called.
@return Empty std::future object
CAUTION: why future?

