name: Build macOS homebrew bottle for aktualizr release page
on: 
  release:
    types: [created]
jobs:
  macOS:
    name: Build macOS homebrew bottle for aktualizr release page
    runs-on: macOS-10.14
    steps:
    - name: Attempt to auto-update recipe and build bottle
      run: |
        curl -O https://raw.githubusercontent.com/advancedtelematic/homebrew-otaconnect/master/aktualizr.rb
        VERSION=${GITHUB_REF#refs/tags/}
        RELEASE_URL="https://github.com/advancedtelematic/aktualizr/releases/download/${VERSION}/"
        sed -i '' -E "s/  version \"20[1-2][0-9].[0-9]+\"/  version \"${VERSION}\"/" aktualizr.rb
        brew install --build-bottle ./aktualizr.rb
        brew bottle --json --no-rebuild --force-core-tap --root-url=${RELEASE_URL} aktualizr
        brew bottle --merge --write --no-commit ./aktualizr--${VERSION}.mojave.bottle.json
        rm aktualizr.rb
        echo "Bottle and recipe creation succeeded!"
        echo "You should now open a PR at https://github.com/advancedtelematic/homebrew/otaconnect"
        echo "Here's the new recipe. It's also attached to this job as an artifact."
        echo "------------------------------------------------------------------------------------"
        brew cat aktualizr | tee aktualizr.rb
        echo "------------------------------------------------------------------------------------"
        mv aktualizr--${VERSION}.mojave.bottle.tar.gz aktualizr-${VERSION}.mojave.bottle.tar.gz
    - name: Upload bottle to github release page
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        brew install ghr 
        VERSION=${GITHUB_REF#refs/tags/}
        ghr -u "${GITHUB_REPOSITORY%/*}" -r "${GITHUB_REPOSITORY#*/}" ${VERSION} aktualizr-${VERSION}.mojave.bottle.tar.gz
    - name: Save recipe as build artifact
      uses: actions/upload-artifact@master
      with:
        name: aktualizr.rb
        path: aktualizr.rb
